# Generated by Django 4.1.4 on 2023-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('height', models.IntegerField()),
                ('birthday', models.DateField(blank=True, null=True)),
                ('careers', models.ManyToManyField(to='api.career')),
                ('genres', models.ManyToManyField(to='api.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('nameRu', models.CharField(blank=True, max_length=255)),
                ('poster', models.FileField(default=None, null=True, upload_to='posters')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('budjet', models.IntegerField()),
                ('moneyUsa', models.IntegerField()),
                ('moneyTotal', models.IntegerField()),
                ('premier', models.DateField()),
                ('premierRu', models.DateField()),
                ('age', models.IntegerField()),
                ('time', models.IntegerField()),
                ('trailer_file', models.FileField(default=None, null=True, upload_to='trailers')),
                ('country', models.ManyToManyField(to='api.country')),
                ('filmDirector', models.ManyToManyField(related_name='filmDirector', to='api.person')),
                ('genre', models.ManyToManyField(to='api.genre')),
                ('screenWriter', models.ManyToManyField(related_name='screenWriter', to='api.person')),
            ],
        ),
    ]
