# Generated by Django 4.1.4 on 2023-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_moneytotal_alter_movie_moneyusa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budjet',
            field=models.CharField(max_length=10),
        ),
    ]
