# Generated by Django 4.1.4 on 2023-02-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movie_budjet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budjet',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='moneyTotal',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='movie',
            name='moneyUsa',
            field=models.CharField(max_length=15),
        ),
    ]
