# Generated by Django 4.1.4 on 2023-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_budjet_alter_movie_moneytotal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(default=None, null=True, upload_to='PersonsImages'),
        ),
    ]
