# Generated by Django 4.1.4 on 2023-04-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='AuthToken',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
