# Generated by Django 4.1.4 on 2023-04-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userinfo_authtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
