# Generated by Django 4.1.4 on 2023-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='AuthToken',
            new_name='authToken',
        ),
        migrations.AddField(
            model_name='user',
            name='refreshToken',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
