# Generated by Django 4.1.4 on 2023-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_authtoken_user_authtoken_user_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(null=True, related_name='FavoritesMovies', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched',
            field=models.ManyToManyField(null=True, related_name='WatchedMovies', to='api.movie'),
        ),
    ]
