# Generated by Django 4.1.4 on 2023-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_user_favorites_alter_user_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='FavoritesMovies', to='api.movie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='watched',
            field=models.ManyToManyField(blank=True, related_name='WatchedMovies', to='api.movie'),
        ),
    ]
